version: '3.7'

services:
  yolo:
    image: bertytech/yolo:latest
    restart: unless-stopped
    network_mode: bridge
    working_dir: /tmp
    volumes:
      - ./data:/data
      - ~/codesign:/codesign:ro
    expose:
      - 8000
    environment:
      - BUILDKITE_TOKEN
      - CIRCLE_TOKEN
      - GITHUB_TOKEN
      - BINTRAY_TOKEN
      - BINTRAY_USERNAME
      - BASIC_AUTH_PASSWORD
      - IOS_PASS
      - IOS_PROV
      - IOS_PRIVKEY
    command:
      - -log-format=json
      - server
      - --cors-allowed-origins=*
      - --max-builds=30
      - --db-path=/data/yolo.sqlite
      - --request-timeout=10s
      - --shutdown-timeout=11s
      - --http-cache-path=/data/httpcache
      - --artifacts-cache-path=/data/artifacts-cache
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
      # traefik specific labels
      - 'traefik.enable=true'
      - "traefik.http.routers.yolo.rule=Host(`${DOMAIN_SANS}`)"
      - 'traefik.http.routers.yolo.service=yolo'
      - 'traefik.http.routers.yolo.entryPoints=https'
      - 'traefik.http.routers.yolo.tls=true'
      - 'traefik.http.routers.yolo.tls.certresolver=cf'
      - "traefik.http.routers.yolo.tls.domains[0].main=${DOMAIN_MAIN}"
      - "traefik.http.routers.yolo.tls.domains[0].sans=${DOMAIN_SANS}"
      - 'traefik.http.services.yolo.loadbalancer.server.port=8000'
      - 'com.datadoghq.ad.logs=[{"source": "go", "service": "yolo"}]'
